language: node_js
before_install:
  - sudo apt-get remove -qq libzmq3 libzmq3-dev
  - sudo apt-get install -qq libzmq-dev
node_js:
  - "0.10"
cache:
  apt: true
env:
  - MODULE='puddle-server'
  - MODULE='puddle-editor'